

import './globals.css'
import { Inter } from 'next/font/google'
import { Navigation } from './components/Navigation'

import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
        <head>
        <meta charset="UTF-8" />
          <title>Arbol de decision ID3</title>
        </head>
        <body className={inter.className}>
          <NavBar/>
          {children}
        </body>
      </html>

    
  )
}
